"""add_channel_profile_generated_column

Revision ID: 0004
Revises: 0003
Create Date: 2025-05-14 15:19:45.409219

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlalchemy_utils.types
from alembic import op

import app.models.base

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_agents",
        sa.Column(
            "channel_profile_generated", sa.Text(), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_agents", "channel_profile_generated")
    # ### end Alembic commands ###
