// This file is auto-generated by @hey-api/openapi-ts

export type AccessToken = {
  token: string;
  token_type?: string;
};

export type CodeRequest = {
  account_id: string;
  phone_number: string;
};

export type CreateAccountRequest = {
  phone_number: string;
  api_id: number;
  api_hash: string;
};

export type HttpError = {
  detail: string;
  status_code: number;
};

export type HttpUnauthorizedError = {
  detail: string;
  status_code: number;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type SignUpRequest = {
  email: string;
  password: string;
  fullname: string | null;
};

export type TgAccount = {
  id: string;
  status: TgAccountStatus;
};

export type TgAccountStatus = "initial" | "sent_code" | "active" | "disabled";

export type User = {
  id: string;
  email: string;
  username: string;
  fullname: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AppAuthSchemasSignInRequest = {
  email: string;
  password: string;
};

export type AppTgAccountsSchemasSignInRequest = {
  account_id: string;
  code: number;
  password?: string | null;
};

export type AuthSignupData = {
  body: SignUpRequest;
  path?: never;
  query?: never;
  url: "/auth/signup";
};

export type AuthSignupErrors = {
  /**
   * Conflict
   */
  409: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
  /**
   * Successful Response
   */
  201: User;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];

export type AuthSigninData = {
  body: AppAuthSchemasSignInRequest;
  path?: never;
  query?: never;
  url: "/auth/signin";
};

export type AuthSigninErrors = {
  /**
   * Unauthorized
   */
  401: HttpUnauthorizedError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthSigninError = AuthSigninErrors[keyof AuthSigninErrors];

export type AuthSigninResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type AuthSigninResponse = AuthSigninResponses[keyof AuthSigninResponses];

export type AuthRefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/refresh-token";
};

export type AuthRefreshTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type AuthRefreshTokenResponse =
  AuthRefreshTokenResponses[keyof AuthRefreshTokenResponses];

export type AuthSignoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/signout";
};

export type AuthSignoutResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AuthSignoutResponse =
  AuthSignoutResponses[keyof AuthSignoutResponses];

export type AuthGetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type AuthGetCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type AuthGetCurrentUserResponse =
  AuthGetCurrentUserResponses[keyof AuthGetCurrentUserResponses];

export type TgAccountsListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/tg/accounts/";
};

export type TgAccountsListResponses = {
  /**
   * Successful Response
   */
  200: Array<TgAccount>;
};

export type TgAccountsListResponse =
  TgAccountsListResponses[keyof TgAccountsListResponses];

export type TgAccountsCreateData = {
  body: CreateAccountRequest;
  path?: never;
  query?: never;
  url: "/tg/accounts/";
};

export type TgAccountsCreateErrors = {
  /**
   * Bad Request
   */
  400: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TgAccountsCreateError =
  TgAccountsCreateErrors[keyof TgAccountsCreateErrors];

export type TgAccountsCreateResponses = {
  /**
   * Successful Response
   */
  201: TgAccount;
};

export type TgAccountsCreateResponse =
  TgAccountsCreateResponses[keyof TgAccountsCreateResponses];

export type TgAccountsSendCodeData = {
  body: CodeRequest;
  path?: never;
  query?: never;
  url: "/tg/accounts/send-code";
};

export type TgAccountsSendCodeErrors = {
  /**
   * Not Found
   */
  404: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TgAccountsSendCodeError =
  TgAccountsSendCodeErrors[keyof TgAccountsSendCodeErrors];

export type TgAccountsSendCodeResponses = {
  /**
   * Successful Response
   */
  200: TgAccount;
};

export type TgAccountsSendCodeResponse =
  TgAccountsSendCodeResponses[keyof TgAccountsSendCodeResponses];

export type TgAccountsSigninData = {
  body: AppTgAccountsSchemasSignInRequest;
  path?: never;
  query?: never;
  url: "/tg/accounts/signin";
};

export type TgAccountsSigninErrors = {
  /**
   * Bad Request
   */
  400: HttpError;
  /**
   * Not Found
   */
  404: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TgAccountsSigninError =
  TgAccountsSigninErrors[keyof TgAccountsSigninErrors];

export type TgAccountsSigninResponses = {
  /**
   * Successful Response
   */
  200: TgAccount;
};

export type TgAccountsSigninResponse =
  TgAccountsSigninResponses[keyof TgAccountsSigninResponses];

export type TgAccountsGetData = {
  body?: never;
  path: {
    account_id: string;
  };
  query?: never;
  url: "/tg/accounts/{account_id}";
};

export type TgAccountsGetErrors = {
  /**
   * Not Found
   */
  404: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TgAccountsGetError = TgAccountsGetErrors[keyof TgAccountsGetErrors];

export type TgAccountsGetResponses = {
  /**
   * Successful Response
   */
  200: TgAccount;
};

export type TgAccountsGetResponse =
  TgAccountsGetResponses[keyof TgAccountsGetResponses];

export type RootData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type RootResponse = RootResponses[keyof RootResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
