services:
  db:
    image: postgres:16.2
    container_name: viralink_db
    command: postgres -c log_statement=all
    volumes:
      - ./.db/:/var/lib/postgresql/data/
      - ./scripts/create_multiple_postgresql_databases.sh:/docker-entrypoint-initdb.d/09_create_multiple_postgresql_databases.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db,db_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
    ports:
      - 5442:5432 # exposed 5442 port for avoiding conflicts with other instances
